// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Export(arg1:boolean,arg2:Array<string>):Promise<main.FileInfo>;

export function Filter(arg1:main.FilterParams):Promise<main.FilterStats>;

export function GetDefaultYear():Promise<number>;

export function GetDetectedFormats():Promise<Array<string>>;

export function GetLoadedFiles():Promise<Array<main.FileInfo>>;

export function GetPage(arg1:number,arg2:number):Promise<Array<main.LogEntry>>;

export function GetTimeRange():Promise<main.TimeRange>;

export function GetWorkingDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListLogFiles(arg1:string,arg2:boolean):Promise<Array<main.FileInfo>>;

export function LoadConfig():Promise<main.Config>;

export function LoadFiles(arg1:Array<string>,arg2:number,arg3:string):Promise<Array<main.FileInfo>>;

export function LoadText(arg1:string,arg2:string,arg3:number,arg4:string):Promise<Array<main.FileInfo>>;

export function PickDirectory():Promise<string>;

export function PickFile():Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function UnloadAll():Promise<void>;
