// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Filter(arg1) {
  return window['go']['main']['App']['Filter'](arg1);
}

export function GetDefaultYear() {
  return window['go']['main']['App']['GetDefaultYear']();
}

export function GetDetectedFormats() {
  return window['go']['main']['App']['GetDetectedFormats']();
}

export function GetLoadedFiles() {
  return window['go']['main']['App']['GetLoadedFiles']();
}

export function GetPage(arg1, arg2) {
  return window['go']['main']['App']['GetPage'](arg1, arg2);
}

export function GetTimeRange() {
  return window['go']['main']['App']['GetTimeRange']();
}

export function GetWorkingDir() {
  return window['go']['main']['App']['GetWorkingDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListLogFiles(arg1, arg2) {
  return window['go']['main']['App']['ListLogFiles'](arg1, arg2);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadFiles'](arg1, arg2, arg3);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function UnloadAll() {
  return window['go']['main']['App']['UnloadAll']();
}
